### ISSUE TITLE
Support for full screen

### ISSUE THREAD

**Issue by yorickreum** [Joran-Dob/flutter_subtitle_wrapper#1]
Good evening,

this plugins looks pretty cool, thanks a lot!
Sadly it doesn't seem to work with full screen videos (at least at iOS). That is a big disadvantage.
Can we help to get this work somehow?

Kind regards from Germany,
Yorick

**Comment by Joran-Dob** [comment]
Hi Yorick, 

Yes, I noticed this as well in a project I was working on. In this project, I was using Chewie. And to get the subtitles to work together with chewie I forked chewie and then wrapped the video player in the subtitle wrapper. 

I can send you the work if you want!

**Comment by yorickreum** [comment]
Hi Joran,

Thanks for your reply!
By now, I solved it as described in #2  – by using your package like an extra widget inside the ChewiePlayerControls, not as a wrapper. This is working perfectly. If anyone is interested, I'm happy to share the our controls widgets.
Since #2 ist merged, I think we can close this issue. Thanks a lot!

Kind regards
Yorick

**Comment by MOOUDE** [comment]
@Joran-Dob  can you please share the code that you used for that, thank you

**Comment by muralikrishnanmt** [comment]
> Hi Yorick,
> 
> Yes, I noticed this as well in a project I was working on. In this project, I was using Chewie. And to get the subtitles to work together with chewie I forked chewie and then wrapped the video player in the subtitle wrapper.
> 
> I can send you the work if you want!

Hi Can you please send that work, in my app subtitle is not working in full screen. I'am also using chewie.

**Comment by Sk4tOoR** [comment]
> ![Screen Shot 06-07-2022 at 06 05 PM](https://user-images.githubusercontent.com/55745378/177551468-bdae76a4-1473-43b3-8847-9ea64f93ca61.png)
> 
> use it like this

Same here. Subtitles in fullscreen are not working. Can't use your code because CustomControls isn't defined anywhere?

**Comment by Joran-Dob** [comment]
Hi, 

I overlooked this project for a bit! Trying to find some time this week to resolve some of the issues or provide some input. Thanks for the information 🚀

**Comment by sumit-coder** [comment]
Thanks for your efforts, but now i am using video_viewer cause i had to use HLS (m3u8) streamable videos with a feature to change the video quality. in video_viewer there is a built-in way to manage subtitles

**Comment by AbMaurya0** [comment]
What to do can u provide code of customcontrols also

**Comment by sumit-coder** [comment]
Hey Foks Sorry for the late replay, the CustomControl widget is a custom widget i made for different control ui buttons using videoPlayerController at its place you can use any widgets
