### ISSUE TITLE
Load local .vtt file

### ISSUE THREAD

**Issue by TejaDroid** [Joran-Dob/flutter_subtitle_wrapper#11]
Hi, Is there a way to load local .vtt file?

**Comment by Joran-Dob** [comment]
Not yet, I will start implementing this for the next release.

If you want you can create an pull for this issue.

**Comment by Joran-Dob** [comment]
Not sure if this will be implemented in this package made the current functionality will stay were you can load the data in your app and then pass it as content to the controller
