### ISSUE TITLE
More styling options

### ISSUE THREAD

**Issue by Joran-Dob** [Joran-Dob/flutter_subtitle_wrapper#18]
Probaly should add more dynamic styling options to the package.

**Comment by alexanderstoll-ibm** [comment]
Hi there!
Nice pub.
Would be great to simply have textStyle as an attribute to pass TextStyle instead the SubtitleStyle. This would push the styling responsibility to the pub consumer.

**Comment by Joran-Dob** [comment]
@alexanderstoll-ibm, thanks! 

Good suggestion. This is gonna be implemented in the scope of this issue.
