### ISSUE TITLE
Not being able to change subtitles dynamically

### ISSUE THREAD

**Issue by Komeyl94** [Joran-Dob/flutter_subtitle_wrapper#21]
I need to change the subtitle dynamically while playing,
I've put the subtitle url in a variable which I change using setState by pressing a button, but the subtitle doesnt change!
Should I be able to do this? If not what am I doing wrong?

I'm using:
subtitle_wrapper_package: ^1.0.2
chewie: ^0.9.10

**Comment by Joran-Dob** [comment]
@Komeyl94 I'm not sure if this is possible currently, I will check it out!

**Comment by Joran-Dob** [comment]
Now fixed in the master branch, you can temporarily add this package directly from the git master branch see: https://dart.dev/tools/pub/dependencies#git-packages 

🎊
