### ISSUE TITLE
subtitle not working in landscape mode

### ISSUE THREAD

**Issue by SayedRagab** [Joran-Dob/flutter_subtitle_wrapper#4]

**Comment by yorickreum** [comment]
Please see my issue #1 about this. I'm quite happy with my workaround.

**Comment by jatin-rajput** [comment]
please help me how to use in full screen

**Comment by rio45ka** [comment]
@yorickreum can you share your code about fix with fullscreen video?

**Comment by yorickreum** [comment]
Quick and dirty: https://gist.github.com/yorickreum/3ecdc94c8c8af2964f9aba566afbcabc
There sure is some room for improvement… I wrote this code quite a while ago, just cleaned it up a little bit and published it. Hope it helps.

**Comment by rio45ka** [comment]
Thank you so much @yorickreum .
I follow your code in video_screen.dart, but I have a problem.
In my SubtitleTextView(), I'm not found parameter for 'subtitleController' and 'videoPlayerController'.
I'm using subtitle_wrapper_package: ^1.0.3.

**Comment by yorickreum** [comment]
It is possible that this was changed... I wrote the code using `subtitle_wrapper_package: ^0.0.10`…
According to https://github.com/Joran-Dob/flutter_subtitle_wrapper/blob/8a462059b297323902a8c8bebe8a733592e86747/lib/subtitle_wrapper_package.dart you can pass `subtitleController` directly to `SubTitleWrapper`,  maybe this is an option…

**Comment by rio45ka** [comment]
Oh I see.
Thank you so much, i will try it.
Thanks

**Comment by sumit-coder** [comment]
https://github.com/Joran-Dob/flutter_subtitle_wrapper/issues/1#issuecomment-1176170030

try this
