### ISSUE TITLE
[request] vtt supports a track of type `metadata` - can flutter_subtitle_wrapper support this?

### ISSUE THREAD

**Issue by davie-robertson** [Joran-Dob/flutter_subtitle_wrapper#40]
As you may know already, since writing this VTT parser; the [VTT standard](https://www.w3.org/TR/webvtt1/#types-of-webvtt-files) supports a variety of `track` or `file` [types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#track_data_types);  subtitles, captions, descriptions, chapters and metadata; the key difference being that metadata is used by scripts and not visible to the user. 

Would is be difficult to modify this repo's code to support the metadata VTT files and trigger an event that a [listener ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#detecting_cue_changes)can act upon when the cue position changes?

**Comment by Joran-Dob** [comment]
@davie-robertson, thanks for providing the request. This looks pretty cool. I am going to look into this could you provide a example VTT file?
