### ISSUE TITLE
Issue with empty lines in the file.

### ISSUE THREAD

**Issue by a-abramov** [Joran-Dob/flutter_subtitle_wrapper#41]
There is an issue with the first empty line. The package displays time `00:00:00.000 --> 00:00:00.500` on the screen after opening instead of an empty line and then it works fine and displaying the text `it is the first text line`

File sample:

```
WEBVTT

00:00:00.000 --> 00:00:00.500


00:00:00.500 --> 00:00:02.400
it is the first text line
```

Package version:
`subtitle_wrapper_package: ^1.0.4`

**Comment by Joran-Dob** [comment]
Thanks for reporting the issue, I am going to look into it.

**Comment by w3ggy** [comment]
@Joran-Dob I made a PR with the temporary solution for this case if someone is looking for it:
https://github.com/Joran-Dob/flutter_subtitle_wrapper/pull/44
