### ISSUE TITLE
RegExp for Subtitle Text doesn't match more than two lines of subtitles

### ISSUE THREAD

**Issue by lrorpilla** [Joran-Dob/flutter_subtitle_wrapper#53]
It seems that if I plug in the following regular expression for subtitles into a test site like [regex101](https://regex101.com/), 
`((\d{2}):(\d{2}):(\d{2})\,(\d+)) +--> +((\d{2}):(\d{2}):(\d{2})\,(\d{3})).*[\r\n]+\s*((?:(?!\r?\n\r?).)*(\r\n|\r|\n)(?:.*))`

The 11th capture group which is used for text will not match more than two lines of text. This is a problem for some subtitles that deliberately newline their subtitles rather than throwing it all in a single line, and mismatches behavior from most video players.

Test String:
```
22
00:02:25,603 --> 00:02:29,524 
This is an example test string
I will match
I will not
```

**Comment by lrorpilla** [comment]
Seems I can throw this regular expression at the problem to solve this for SRT:
`((\d{2}):(\d{2}):(\d{2})\,(\d+)) +--> +((\d{2}):(\d{2}):(\d{2})\,(\d{3})).*[\r\n]+\s*(^[\s\S]*?(?=\n{2,}))`

The SRT format always has a blank line at the end of text `^[\s\S]*?(?=\n{2,})` as described in this [SRT specification].(https://www.matroska.org/technical/subtitles.html#srt-subtitles)

> It consists of four parts, all in text:
>
>1. A number indicating which subtitle it is in the sequence. 
>2. The time that the subtitle appears on the screen, and then disappears. 
>3. The subtitle itself. 
>4. A blank line indicating the start of a new subtitle.

So, I replace `(?:(?!\r?\n\r?).)*(\r\n|\r|\n)(?:.*)` for `^[\s\S]*?(?=\n{2,})`.

**Comment by Joran-Dob** [comment]
Not sure if this is still an problem for you, if so feel free to reopen!
