### ISSUE TITLE
Add  background to subtitle with SubtitleBorderStyle

### ISSUE THREAD

**Issue by markfili** [Joran-Dob/flutter_subtitle_wrapper#59]
Is it possible to add a background to subtitle text?

I tried using the subtitle border style property but got some questionable results...

code:
```
SubTitleWrapper(
  videoPlayerController: _videoPlayerController,
  subtitleController: _subtitleController,
  subtitleStyle: SubtitleStyle(
    fontSize: 25,
    hasBorder: true,
    borderStyle: SubtitleBorderStyle(
      style: PaintingStyle.stroke, // fill didn't work
      color: Color(0x803F444B),
      strokeWidth: 20,
    ),
    textColor: Colors.white,
    position: SubtitlePosition(
      bottom: 150,
    ),
  ),
  videoChild: Chewie(controller: _chewieController),
)
```

What was expected:
![image](https://user-images.githubusercontent.com/3738182/140781701-2ccbfc78-cd37-4063-9092-3a27ea0a3a3c.png)

What was delivered:
![image](https://user-images.githubusercontent.com/3738182/140781741-51f1d54b-913e-4b38-b72b-28d5e9c242fa.png)

**Comment by Joran-Dob** [comment]
Added in #67
