### ISSUE TITLE
Reset subtitles

### ISSUE THREAD

**Issue by markfili** [Joran-Dob/flutter_subtitle_wrapper#60]
Is it ok to request for a feature to reset subtitles to the state they were in when the video started?

With the current Bloc implementation, that would mean yielding an empty state so that the screen is cleared if for example: the video was rewinded with `seekTo(Duration.zero))`.
Either that or a `reset()` method could work, too, for when rewinding the video programmatically.

**Comment by Joran-Dob** [comment]
I think this should work with #66, please let me know if it does not work and is still needed.
