### ISSUE TITLE
Subtitles dont stop when they have to

### ISSUE THREAD

**Issue by Soffset** [Joran-Dob/flutter_subtitle_wrapper#74]
**Description**
Subtitles dont stop and disappear when they have to but only when they get replaced by the next subtitle

For example my subtitle

`00:00:53.140 --> 00:00:54.710
Better head to work.`

should stop at 00:00:54.710 but keeps going until it gets replaced by the next one.

Im loading the subtitles file from url exactly like in the examples:

`final SubtitleController subtitleController = SubtitleController(
    subtitleUrl:
        "eng.vtt",
    subtitleType: SubtitleType.webvtt,
  );`

Am i missing something or doing something wrong?
I tried using chewie or just video_player but it keeps happening, am i the only one having this issue?

**Comment by Joran-Dob** [comment]
Hi, 

I overlooked this project for a bit! Trying to find some time this week to resolve some of the issues or provide some input. Thanks for the information 🚀

**Comment by tele4rom** [comment]
I have the same problem. Are there any solutions?

**Comment by Joran-Dob** [comment]
Fixed the issue and uploaded a new package version to pub.dev.

https://pub.dev/packages/subtitle_wrapper_package/changelog
