### ISSUE TITLE
FontWeight? Bolding subtitles...

### ISSUE THREAD

**Issue by acavazos1982** [Joran-Dob/flutter_subtitle_wrapper#77]
If i want my subtitles to be BOLDED how would i do that?

**Comment by Joran-Dob** [comment]
Currently, it is not possible, you could open a PR for the functionality. I will keep this open as a reference!

**Comment by Srujithchaithanya1** [comment]
Hey, I want to work on this issue!

**Comment by Adbhutashra** [comment]
Also add other properties as well like textBorder , textShadow and also alignment instead of subtitle position.

**Comment by Joran-Dob** [comment]
You can do this now by passing textStyle to the controller, see the example at https://pub.dev/packages/subtitle_wrapper_package/versions/3.0.0-dev.1/example
