### ISSUE TITLE
Landscape subtitle 

### ISSUE THREAD

**Issue by MOOUDE** [Joran-Dob/flutter_subtitle_wrapper#9]
The plugin now seems not to support the subtitles on landscape mode, so it would be great if fix this

**Comment by Joran-Dob** [comment]
@MOOUDE For this the best option is to fork for example [(Chewie)](https://pub.dev/packages/chewie) and then wrap the full screen video player with this wrapper.

**Comment by hasanm08** [comment]
@MOOUDE could you resolve the problem?
